ibex:
  url: "https://api-sandbox.poweredbyibex.io"
  email:
  password:
  webhook:
    uri: # external uri defined in overrides
    port: 4008
    secret: "not-so-secret"

# See Foreign Exchange Rates: https://www.firstglobal-bank.com/
exchangeRates:
  USD:
    JMD:
      bid: 150
      ask: 160

cashout:
  minimum:
    amount: 0
    currency: USD
  maximum:
    amount: 100 # $1
    currency: USD
  accountLevel: 2
  fee: 200 # basis points
  duration: 600 # seconds
  email:
    to: # add to the overrides.yaml
    from: "notifications@getflash.io"
    subject: "New Cashout"
