# future admins should be added via admin-api.
admin_accounts:
  - role: "bankowner"
    phone: "+16505554334"

ibex:
  url: "https://api-sandbox.poweredbyibex.io"
  authUrl: "https://auth.hub.sandbox.poweredbyibex.io"
  email: ""
  password: "Ibex@1234"
  apiKey: "sk-test-3bd6463c9cd77c3d8858c60b9997d0c6"
  webhook:
    uri: "" # external uri defined in overrides
    port: 4008
    secret: "not-so-secret"

bridge:
  enabled: true
  apiKey: "sk-test-3bd6463c9cd77c3d8858c60b9997d0c6"
  baseUrl: "https://api.sandbox.bridge.xyz/v0"
  minWithdrawalAmount: 10
  webhook:
    port: 4009
    replaySecret: "also-not-so-secret"
    publicKeys:
      kyc: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxrV+s8CvC0+s1W6vZG52
        5eozo6W6HzkTcLQMWDoEzQX+ulEoYH2fPuXeupi11MdVLpEqNqYas8LD3BIf/c9H
        kK54V8vnXNwoHa5ROp/Gjp3B17q3wGfjLa8bQJoJZFWd9W+e3TjUohCDNpeD/qv+
        bkY2y3b1QixmXKK3REw35sfiEe5NkGMU4aEfXhZieIZ1mKXLsIgsgrIpv9BFwQr5
        +h3R7Vv3hGKVgSZHnRMa9F1/go8v5Au8gj+9w0LxxRJikoJCubI6igaTCivibxuo
        QXWfFylw6m7eQTvZDQz70pnUEakofRlvKasetbyKmvLzMhuRHeqsxgi8C4ZCx7MP
        dwIDAQAB
        -----END PUBLIC KEY-----
      deposit: | 
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxrV+s8CvC0+s1W6vZG52
        5eozo6W6HzkTcLQMWDoEzQX+ulEoYH2fPuXeupi11MdVLpEqNqYas8LD3BIf/c9H
        kK54V8vnXNwoHa5ROp/Gjp3B17q3wGfjLa8bQJoJZFWd9W+e3TjUohCDNpeD/qv+
        bkY2y3b1QixmXKK3REw35sfiEe5NkGMU4aEfXhZieIZ1mKXLsIgsgrIpv9BFwQr5
        +h3R7Vv3hGKVgSZHnRMa9F1/go8v5Au8gj+9w0LxxRJikoJCubI6igaTCivibxuo
        QXWfFylw6m7eQTvZDQz70pnUEakofRlvKasetbyKmvLzMhuRHeqsxgi8C4ZCx7MP
        dwIDAQAB
        -----END PUBLIC KEY-----
      transfer: "<replace>"
    timestampSkewMs: 300000

# See Foreign Exchange Rates: https://www.firstglobal-bank.com/
exchangeRates:
  USD:
    JMD:
      bid: 150
      ask: 160

cashout:
  enabled: false
  minimum:
    amount: 0
    currency: USD
  maximum:
    amount: 100 # $1
    currency: USD
  accountLevel: 2
  fee: 200 # basis points
  duration: 600 # seconds
  email:
    to: "" # add to the overrides.yaml
    from: "notifications@getflash.io"
    subject: "New Cashout"

# credentials and accounts defined in the erpnext restore script
frappe:
  url: http://frontend.local:8080
  sitename: frontend # default sitename for frappe docker container
  credentials:
    apiKey: "2701937b221364c"
    apiSecret: "a05ab1998d20828"
  erpnext:
    accounts:
      ibex:
        operating: "Ibex Operating - F"
      cashout: "Cashout Payables (JMD) - F"
      serviceFees: "Service Fees - F"

sendgrid:
  apiKey: "<replace>"

# FCM topic names for push notifications.
# Replace "dev" with a unique identifier to avoid accidentally sending to other environments.
fcmTopics:
  - name: "dev-EMERGENCY"
    default: true
  - name: "dev-ATTENTION"
    default: true
  - name: "dev-INFO"
    default: false
  - name: "dev-MARKETING"
    default: false
