#!/bin/bash

set -e

if [[ $(which ytt) == "" ]]; then
  echo "You will need to install ytt to repipe. https://carvel.dev/ytt/"
  exit 1
fi


## Script requires a FLY_TARGET (e.g flash-ci) and PIPELINE_VALUES (e.g "/path/to/flash-values.yml) as env variables
target="${FLY_TARGET:-local}"
team=main # dev
pipeline="${PIPELINE_NAME:-flash-app}"
values="${PIPELINE_VALUES}"

TMPDIR=""
TMPDIR=$(mktemp -d -t repipe.XXXXXX)
trap "rm -rf ${TMPDIR}" INT TERM QUIT EXIT

ytt -f ci > ${TMPDIR}/pipeline.yml

echo "Updating pipeline @ ${target}"

fly -t ${target} set-pipeline --team=${team} -p flash-app -c ${TMPDIR}/pipeline.yml -l ${values}
fly -t ${target} unpause-pipeline --team=${team} -p flash-app
